name: Mirror Subfolder

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the source repository
    - name: Check out source repository
      uses: actions/checkout@v3

    # Step 2: Set up Git
    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    # Step 3: Filter the Subfolder
    - name: Filter subfolder
      run: |
        git sparse-checkout init --cone
        git sparse-checkout set backend
        git checkout
        rm -rf .git/sparse-checkout

    # Step 4: Push to Target Repository
    - name: Push to target repository
      env:
        TARGET_REPO: https://${{ secrets.GITHUB_TOKEN }}github.com/Annabeccam/frontendrepo.git
      run: |
        git remote add target ${{ env.TARGET_REPO }}
        git add .
        git commit -m "Mirror subfolder"
        git push --force target main
